### ISSUE TITLE
Serverside Error

### ISSUE THREAD

**Issue by Nessaj1** [Tommy228/TTT_Spectator_Deathmatch#11]
[ERROR] addons/tttspecdm/lua/cl_spectator_deathmatch.lua:516: attempt to index global 'GAMEMODE' (a nil value)
1. unknown - addons/tttspecdm/lua/cl_spectator_deathmatch.lua:516
2. include - [C]: -1
3. unknown - addons/tttspecdm/lua/autorun/client/ttt_spec_dm_ autorun.lua:4

Always people getting this error if they join the server or a map switch is happening. We are playing on TTT

**Comment by Tommy228** [comment]
Fixed
