### ISSUE TITLE
TTT Haste Time

### ISSUE THREAD

**Issue by Nessaj1** [Tommy228/TTT_Spectator_Deathmatch#12]
People on my server found a little bug. If you join and leave the deathmatch traitors get more time. We are playing TTT with haste mode and every time a player die you get 15 seconds normally.

P.S.: Maybe you also know something about my problem what I posted in the thread (That people spawn under the ground sometimes, most of the time after a map change if I using the newest github update)

**Comment by Tommy228** [comment]
I fixed this a long time ago when I started coding specdm. Maybe it's a conflict

**Comment by Nessaj1** [comment]
Damn :) I will try to find the conflict, thanks for the response
