### ISSUE TITLE
Fall damage from Spectator DM players can be heard by live players.

### ISSUE THREAD

**Issue by DetectDefective** [Tommy228/TTT_Spectator_Deathmatch#13]
Noticeable on somewhat vertical maps, if a SpecDM player falls, you can hear the generic hurt sound from fall damage as a live player in TTT.

**Comment by Kefta** [comment]
This can only be fixed if proper PAS functions are added to GMod.

**Comment by CSchulz** [comment]
Overwriting https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/terrortown/gamemode/player.lua#L863 will not help?

**Comment by markusmarkusz** [comment]
@CSchulz
This would be the easiest solution.
Using a hook that handles SpecDM Falldamage.

**Comment by CSchulz** [comment]
Overwriting the hook and check if player is a Ghost otherwise play original hook.
