### ISSUE TITLE
Burn

### ISSUE THREAD

**Issue by deinemudda32** [Tommy228/TTT_Spectator_Deathmatch#16]
If you play on some MC Maps you can burn and interact with some objects.
Just a check for this to prevent this, would be good.

**Comment by CSchulz** [comment]
Which maps do you mean? I would try it on my own.

**Comment by deinemudda32** [comment]
ttt_minecraft_b5

**Comment by CSchulz** [comment]
It doesn't affect only maps, fire and nades doing the same.

**Comment by InstinktOwner** [comment]
Same Problem here

**Comment by Kefta** [comment]
This could probably be fixed by detouring the Use function, but that's really hacky.

**Comment by CSchulz** [comment]
Why not returning true in EntityTakeDamage hook? ("Return true to completely block the damage event")

https://github.com/Tommy228/TTT_Spectator_Deathmatch/blob/ddc12f50349bc73e3683731df6f1362dc0c365c0/lua/sv_specdm_overrides.lua#L180

**Comment by Kefta** [comment]
That doesn't stop the interaction. And that breaks other hooks that might be searching for burn damage

**Comment by CSchulz** [comment]
Oh okay, didn't know that. I was expecting that burn sound and damage handling belongs together.

I meant, you should only return true in DM not globally. There is a condition searching for ghost.

**Comment by markusmarkusz** [comment]
This needs a tricky workaround.
Even if you block the damage the sound will be played.
You have to stop the sound from being played if the reason for the sound is a SpecDM User. I have used a EntityEmitSound Hook.

**Comment by CSchulz** [comment]
Could it be a performance issue if you overwrite that hook? I am hesitating overwriting such hooks.

**Comment by CSchulz** [comment]
@markusmarkusz Opened a PR right now.
