### ISSUE TITLE
Sometimes people join the DM while living and get invisible for living players

### ISSUE THREAD

**Issue by CSchulz** [Tommy228/TTT_Spectator_Deathmatch#17]
Sometimes it happens that alive players join the DM and got invisible for living players.

They appearing normal in DM and are invisible for living players.

**Comment by CSchulz** [comment]
![invisible_ghost](https://cloud.githubusercontent.com/assets/1520593/6625636/8c66cdb2-c8f1-11e4-9e86-d6ce4a30e864.jpg)

**Comment by CSchulz** [comment]
![invisible_ghost](https://cloud.githubusercontent.com/assets/1520593/6625667/bd918a8a-c8f1-11e4-9263-7808147fe393.jpg)

**Comment by MattTheEmp** [comment]
[ERROR] addons/ttt spectator deathmatch/lua/cl_spectator_deathmatch.lua:345: attempt to call method 'DrawModel' (a nil value)
  1. unknown - addons/ttt spectator deathmatch/lua/cl_spectator_deathmatch.lua:345

I get this error too. i believe this is the error you are looking for.

**Comment by Tommy228** [comment]
It's caused by the NWVars update, a gmod update with a hotfix should be coming.

**Comment by CSchulz** [comment]
in the last time I didn't see it again.

**Comment by CSchulz** [comment]
It appears again ... Really bad ...

**Comment by CSchulz** [comment]
We have found a case when it happens ...

If someone is dead, joins the DM and changes its name, the server will kick him for name changing. If he joins again he is invisible.

**Comment by InstinktOwner** [comment]
I have the same Problem here :/

**Comment by InstinktOwner** [comment]
I have the same Problem here :/

**Comment by InstinktOwner** [comment]
I have the same Problem here :/

**Comment by P4sca1** [comment]
Same here. With the next GMod Update, the NWVars will ber olled back completely. This will hopefulyl fix this issue.

**Comment by CSchulz** [comment]
It would be possible to revert the changes to get it working with the defect NWVars.
@Tommy228 what do you think? I would try it, test it locally and create a pull request. Or are you interested in doing it?

**Comment by Tommy228** [comment]
@CSchulz try it

**Comment by CSchulz** [comment]
@MinIsMin Why is this closed?

**Comment by MinIsMin** [comment]
Currently, I can't reproduce the error and NWVars are working on the tested servers. If it's not working for you, feel free to comment.
