### ISSUE TITLE
Click to (re)spawn player

### ISSUE THREAD

**Issue by CSchulz** [Tommy228/TTT_Spectator_Deathmatch#18]

**Comment by markusmarkusz** [comment]
What is meant with “Click to respawn“?
What do you want?

**Comment by CSchulz** [comment]
The player should not automatically spawn.

**Comment by markusmarkusz** [comment]
What about adding a config option or a convar so players/server owners can control this? Implementing this would be easy.

**Comment by CSchulz** [comment]
Would be fine for me. I had no time to implement this otherwise I had created a PR.

**Comment by markusmarkusz** [comment]
I'll write something for you later :).

**Comment by MinIsMin** [comment]
Should the ghost wait the amount of time set in SpecDM.RespawnTime or should pressing a key instantly respawn him?

**Comment by CSchulz** [comment]
I would say both. You have to wait some time and if the time is up you can respawn.

**Comment by MinIsMin** [comment]
Fixed in https://github.com/Tommy228/TTT_Spectator_Deathmatch/commit/f61a38c2ddb2e524f6443bbf08a63057646820e5
