### ISSUE TITLE
Join message

### ISSUE THREAD

**Issue by comedinha** [Tommy228/TTT_Spectator_Deathmatch#2]
"20:09:46 - comedinhajoined the deathmatch!"

Correct is
20:09:46 - comedinha has joined the deathmatch!

**Comment by Kefta** [comment]
This is fixed: https://github.com/Tommy228/TTT_Spectator_Deathmatch/blob/6ade38bb3f029b0307f59543cc4171cbb572fcdf/lua/cl_spectator_deathmatch.lua#L30
