### ISSUE TITLE
Hands at side

### ISSUE THREAD

**Issue by npd1124** [Tommy228/TTT_Spectator_Deathmatch#23]
For some reason if you look at a player it shows that their hands are at their side holding their weapon as shown here http://gyazo.com/565aba3be24d154aa2465f1120c3d083. I am also getting this in console, Im pretty sure it has something to do with it but not positive "SWEP:SetWeaponHoldType - ActIndex[ "" ] isn't set! (defaulting to normal)"

**Comment by Kefta** [comment]
That's a problem with your weapons
