### ISSUE TITLE
On ttt_minecraft_b5 if a traitor is in the traitor room (near tower) and someone walks into it when in deathmatch/ghost mode, it kills the traitor inside. 

### ISSUE THREAD

**Issue by backstab42** [Tommy228/TTT_Spectator_Deathmatch#25]
Is there any fix for this?

**Comment by InstinktOwner** [comment]
I have the same problem

**Comment by Kefta** [comment]
A special exception would have to be made for that trigger, which would require the trigger name.

**Comment by Linkfan123** [comment]
Ewww. We'd have to fix that.
Contact the map developer, ask for the trigger names of the T-room and an explanation what they do. THEN we can get rolling.

**Comment by Violat0r** [comment]
The tnt cart also blows up when a person in dm walks into it. The nether portal trap is also set off by a person in dm going though it.

Out solution to this problem was to fix the map lol.

**Comment by MinIsMin** [comment]
There's currently no fix, the map needs to be updated.

**Comment by MinIsMin** [comment]
What would the fix be?

**Comment by markusmarkusz** [comment]
Use a AcceptInput Hook.
