### ISSUE TITLE
On some maps, ghosts can see shadows of living players

### ISSUE THREAD

**Issue by MinIsMin** [Tommy228/TTT_Spectator_Deathmatch#47]
On some maps (e.g. "ttt_forest_final") ghost can see the shadows of living players regardless the setting "show alive players".
I don't know why this bug only occurs on some maps.

**Comment by mcNuggets1** [comment]
Not every map has 100% working shadows.

**Comment by Violat0r** [comment]
Easy fix just use ply:DrawShadow(false) for alive players as a ghost and if we don't have it already for ghosts as well.
