### ISSUE TITLE
IsGhost error

### ISSUE THREAD

**Issue by comedinha** [Tommy228/TTT_Spectator_Deathmatch#50]
The AutoIncludeWeapons have bug
all IsGhost function stop work...

**Comment by comedinha** [comment]
@find the problem.

**Comment by MinIsMin** [comment]
Turning AutoIncludeWeapons to false in config file doesn't help (for now)?

**Comment by MinIsMin** [comment]
Please test if it's working now.
When not please paste the lua error here.

**Comment by comedinha** [comment]
No have erros on last update...
