### ISSUE TITLE
Users in SpecDM block names of alive users

### ISSUE THREAD

**Issue by Delta7x** [Tommy228/TTT_Spectator_Deathmatch#57]
Callouts being blocked was fixed (Thanks, by the way! <3), however it seems a new issue has come because of that.

If a SpecDM ghost is inbetween two players like so:

P = Player
G = Ghost
P1 G P2

When Player 1 looks at Player 2 their name does not show up and it looks like they have a disguiser enabled though you're still able to call them out as "Player2 is a Traitor!".

**Comment by MinIsMin** [comment]
The bug also occurs in situation like these:
G1 P G2

I can't fix it until tomorrow, the v1.8 release date. Will be included in v1.9.

**Comment by MinIsMin** [comment]
I made a testing branch which should fix this bug:
https://github.com/Tommy228/TTT_Spectator_Deathmatch/tree/testing

If you can, please check if it's working for you.
