### ISSUE TITLE
After adding Spectator Deathmatch you can't spectate live players

### ISSUE THREAD

**Issue by Delta7x** [Tommy228/TTT_Spectator_Deathmatch#58]
Pretty much the title

**Comment by MinIsMin** [comment]
Fixed by @mcNuggets1 xD
Bug was introduced in https://github.com/Tommy228/TTT_Spectator_Deathmatch/commit/c9d963391385d115440f602bc14cf24b2b9d8746#diff-dfff33395cd2f31d3eca5431f44bd6efL126
