### ISSUE TITLE
A lot of bugs

### ISSUE THREAD

**Issue by dok441** [Tommy228/TTT_Spectator_Deathmatch#63]
1.The first and easiest gun in the invisible hand, the model is specified incorrectly
2. Murder statistics not recorded
3. See nicknames of players, if you use quick commands I'm with someone.
4.Many guns have special T, work for the people in deathmatches.
5.Not working sounds and no inscriptions, although all is configured perfectly.
6.No display in the list, the list of players, in all settings

**Comment by MinIsMin** [comment]
What version are you using (e.g. Workshop (from EGM P4sca1), GitHub master, GitHub stable release)?

**Comment by dok441** [comment]
GitHub master Use this.
GitHub stable release But, I tried this, the tab is there just not working, for the rest I can not say exactly, so test with bots.

**Comment by MinIsMin** [comment]
I don't quite understand your english, maybe I can translate it better if you write in your mother language, Russian.

**Comment by dok441** [comment]
GitHub master Я, использую его на основе.
GitHub stable release Я, его тестировал, тоже самое по крайне мере с TAB.

**Comment by MinIsMin** [comment]
Я понимаю, что вы используете версию GitHub, но не ошибки.

Что я получаю от вашего комментария:
1: ?
2: Статистика F7 не записывается (они работают на моем конце)
3: Я буду исследовать быстрые команды
4: Some traitor weapons are usable by ghosts which shouldn't be
5: Kill Sounds («Unstoppable») не работают (они работают на моем конце)
6: ? (Может быть, как пункт 2)

**Comment by dok441** [comment]
1 .Glock, невидимый в руках, модель указана неправильно.
2. Статистика в F7 не записывает убийства, только часы.
3. Если использовать быстрые команды, "Предатель ...", то если случайно будет проходить человек из DM, укажет на него.
4. Многие Специальные оружия предателей  срабатывают на людей из DM.
5. Звуки или же надписи не работают, хотя функция включена
6. В Tab нету отображение  списка играющих игроков.

**Comment by MinIsMin** [comment]
Точки 1, 2, 4, 5 и 6 выглядят как проблемы с другими аддонами, поскольку он обычно работает на других серверах.

Попробуйте деактивировать все / некоторые дополнения и проверить, работает ли он.

**Comment by MinIsMin** [comment]
Closing this issue since these bugs are already fixed and seem to be caused by another addon.
