### ISSUE TITLE
Pointshop incompatiblity

### ISSUE THREAD

**Issue by MinIsMin** [Tommy228/TTT_Spectator_Deathmatch#64]
**What?** When using Pointshop (2) people's accessoirs aren't hidden when being in SpecDM and can be seen by everyone.

**Which version?** Every SpecDM version

**Why?** The're no calls to hide the accessoirs.

**Comment by mcNuggets1** [comment]
Pointshop 2 should add support for specdm not otherwise.

**Comment by monster010** [comment]
`pac.TogglePartDrawing(ply, false)` for hide
`pac.TogglePartDrawing(ply, true)` for show

**Comment by MinIsMin** [comment]
Pushed a first fix: https://github.com/Tommy228/TTT_Spectator_Deathmatch/commit/a3f01809ba04cf8a7eaa5100be0f876cc3e965d2 , second coming tomorrow (hopefully).

What works:
Ghost can't see alive hats
Alive can't see ghosts hats

What doesn't work yet:
Ghost can't see ghosts hats (but they should)

**Comment by MinIsMin** [comment]
It's (currently) not possible to let ghosts see other ghost's hats due to pac handling dead players.
This issue looks fixed: No more flying hats or trails.
