### ISSUE TITLE
Flashlight Showing up In SpecDM

### ISSUE THREAD

**Issue by baronvonhaxor** [Tommy228/TTT_Spectator_Deathmatch#66]
I have an issue with the spectators in DM being able to use their flashlights which makes their bodies flicker and their flashlights visible to living players. I previously issued a pull request for a fix which turned out to also not work so I'm stuck for fixes.

**Comment by MinIsMin** [comment]
The (default gmod-) flashlight should be disabled for ghosts in SpecDM.
Did you test it on a (local) server without addons?

**Comment by baronvonhaxor** [comment]
The issue was caused by https://www.gmodstore.com/scripts/view/2604 and I have sent the creator a fix for this.
