### ISSUE TITLE
Weapon Shadow Error

### ISSUE THREAD

**Issue by Violat0r** [Tommy228/TTT_Spectator_Deathmatch#67]
Error in hook PrePlayerDraw: addons/ttt_deathmatch_8_27_2017/lua/cl_spectator_deathmatch.lua:120: Tried to use a NULL entity!
stack traceback:
	[C]: in function 'DrawShadow'
	addons/ttt_deathmatch_8_27_2017/lua/cl_spectator_deathmatch.lua:120: in function 'fn'
	addons/ulib_08_22_2017/lua/ulib/shared/hook.lua:109: in function <addons/ulib_08_22_2017/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'
	lua/.dragondildos/rc1/../nul/32f11bce8bf02aa4a1681e73cbf17c5552f649fc337baf1756d626444b83ed8c.lua:59: in function <lua/.dragondildos/rc1/../nul/32f11bce8bf02aa4a1681e73cbf17c5552f649fc337baf1756d626444b83ed8c.lua:53>
	[C]: in function 'DrawModel'
	gamemodes/base/entities/weapons/weapon_base/cl_init.lua:160: in function <gamemodes/base/entities/weapons/weapon_base/cl_init.lua:158>

[ERROR] 
  1. unknown - [C]:-1
   2. DrawModel - [C]:-1
    3. unknown - gamemodes/base/entities/weapons/weapon_base/cl_init.lua:160

Error in hook PrePlayerDraw: addons/ttt_deathmatch_8_27_2017/lua/cl_spectator_deathmatch.lua:120: Tried to use a NULL entity!
stack traceback:
	[C]: in function 'DrawShadow'
	addons/ttt_deathmatch_8_27_2017/lua/cl_spectator_deathmatch.lua:120: in function 'fn'
	addons/ulib_08_22_2017/lua/ulib/shared/hook.lua:109: in function <addons/ulib_08_22_2017/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

Error in hook PrePlayerDraw: addons/ttt_deathmatch_8_27_2017/lua/cl_spectator_deathmatch.lua:120: Tried to use a NULL entity!
stack traceback:
	[C]: in function 'DrawShadow'
	addons/ttt_deathmatch_8_27_2017/lua/cl_spectator_deathmatch.lua:120: in function 'fn'
	addons/ulib_08_22_2017/lua/ulib/shared/hook.lua:109: in function <addons/ulib_08_22_2017/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

**Comment by MinIsMin** [comment]
I don't know what's causing it but maybe it's from a deathrun script ([dragondildo](https://facepunch.com/showthread.php?t=1406281)) which is autoloaded (`garrysmod/lua/.dragondildos/`).

Should be fixed with https://github.com/Tommy228/TTT_Spectator_Deathmatch/commit/d03456691dbdcd701f0f29aae9db9842683378cb
