### ISSUE TITLE
Burning alive players when dead in Spectator deathmatch

### ISSUE THREAD

**Issue by Quinlan102** [Tommy228/TTT_Spectator_Deathmatch#70]
If you joined specDM then jump in a lava pit then leave specDM and quickly spectate someone else you can burn them and kill them

**Comment by MinIsMin** [comment]
Can not confirm this.
Does the player jumping in the lava need to die?
What version of "Spectator Deathmatch" do you use?
Did you try reproducing this bug without other addons?

**Comment by Quinlan102** [comment]
I am running the newest version of SpecDM i know this because im running the newest version of TTT
Here is a video of me doing it on my server.
http://www.mediafire.com/file/tvk7r7foqq2ara4/Sequence_02.mp4
All TTT servers that i have played on have this bug!!

**Comment by MinIsMin** [comment]
You can run an old version of SpecDM on the newest version of TTT.
In the newest version of SpecDM ([v1.9.8](https://github.com/Tommy228/TTT_Spectator_Deathmatch/releases/tag/v1.9.8)) ghosts [can not be ignited](https://github.com/Tommy228/TTT_Spectator_Deathmatch/commit/dd87f9a328afebeb5b1bbebe1a14cfc7f8fc8759#diff-f4ba11eb355c0b5f897d4bedcd05a135R188).

You either use an old version of SpecDM or an addon tampers with the `Tick_Ghost` hook.
Please check the content of your VERSION file in the SpecDM folder.
