### ISSUE TITLE
Able to see players names walking around

### ISSUE THREAD

**Issue by derekstephen** [Tommy228/TTT_Spectator_Deathmatch#78]
### What happened?
While alive, if someone is in specdm, you can see their name when you hover your crosshair over them.

### Are there any lua errors in the console?
No

### Are you using a beta branch of GarrysMod? (No, prerelease, dev)
No

### What version of TTT Spectator Deathmatch do you use? (e.g. Workshop, GitHub master, GitHub stable release)
TTT Spectator Deathmatch version: 1.9.8

Photo: https://i.imgur.com/Z1tNpVi.jpg

**Comment by MinIsMin** [comment]
1.9.8 is not the newest version avalible, [1.10 was released](https://github.com/Tommy228/TTT_Spectator_Deathmatch/releases/tag/v1.10) which fixed that issue.

**Comment by derekstephen** [comment]
Updated and no longer and issue!
