### ISSUE TITLE
Serverside Error

### ISSUE THREAD

**Issue by npd1124** [Tommy228/TTT_Spectator_Deathmatch#8]
I am getting this error serverside

L 12/06/2014 - 17:18:49: Lua Error: 
[ERROR] addons/deathmatch/lua/sh_spectator_deathmatch.lua:34: attempt to call method 'IsPlayer' (a nil value)
  1. fn - addons/deathmatch/lua/sh_spectator_deathmatch.lua:34
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:184

**Comment by petravic** [comment]
I fixsed all thia issues but tommy is not accepting pull reqs so i gived up
